# workflow(스크립트 전체)의 이름을 지정
name: Deploy to EC2 With Jar
# push 이벤트 지정 (트리거 동작)
# main branch에 push 될 때마다 workflow가 실행되도록 지정
on:
  push:
    branches:
    - main
jobs:
  # 작업의 이름 지정
  build-and-deploy:
    # 가상의 작업 공간(가상 서버)에 ubuntu 설치
    runs-on: ubuntu-latest
    steps:
      # 소스 코드를 ubuntu로 가져옴
    - uses: actions/checkout@v2
    # github 소스 코드를 가상의 작업 공간
    - name: Set up JDK 11
      # 쉽게 자바를 설치할 수 있는 라이브러리를 받아와서 java 설치
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Build with Gradle
      # 배포할 폴더로 이동
      working-directory: ./ordering
      # 실행 가능한 jar파일만 생성 (plain jar 미생성)
      run: |
        chmod +x ./gradlew
        ./gradlew bootJar
    - name: Copy jar to EC2
      uses: appleboy/scp-action@master
      with:
        # Github Secret 처리
        host: ${{ secrets.EC2_HOST1 }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        source: "./ordering/build/libs/*.jar"
        # 우분투 경로
        target: "/home/${{ secrets.EC2_USERNAME }}"