name: Deploy to AWS S3

on:
  push:
    branches:
    - dev
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: setup node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: npm install
      working-directory: ./ordering-frontend
      run: npm install

    - name: npm build
      working-directory: ./ordering-frontend
      run: npm run build

    - name: setup aws cli
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{secrets.AWS_S3_ACCESS_KEY}}
        # iam 사용자에서 액세스키 발급
        aws-secret-access-key: ${{secrets.AWS_S3_SECRET_ACCESS_KEY}}
        aws-region: "ap-northeast-2"
    - name: deploy to s3
      run: |
        aws s3 cp ./ordering-frontend/dist s3://order-system-qoth/ --recursive
