# 도커허브에 이미지 push, ec2에 ssh로그인, dockerhub에 업로드된 이미지를 ec2에서 pull

name: Deploy to EC2 With Docker
on:
  push:
    branches:
    - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      #  소스 코드를 ubuntu로 가져옴
    - uses: actions/checkout@v2
      # 도커 이미지 build
    - name: Build Docker Image
      working-directory: ./ordering
      run: docker build -t bny1324/ordering:v2 .
      # 도커허브 로그인
    - name: DockerHub Login
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
      # 도커 이미지 push
    - name: Push Docker Image to DockerHub
      run: docker push bny1324/ordering:v2

